In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [2]:
data=pd.read_csv('Churn_Modelling.csv')

In [3]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [5]:
data.head( )

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
label_encoder=LabelEncoder()
data['Gender']=label_encoder.fit_transform(data['Gender'])

In [9]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [14]:
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder=OneHotEncoder()
geography_encoded=one_hot_encoder.fit_transform(data[['Geography']])

In [15]:
geography_encoded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [17]:
one_hot_encoder.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [18]:
geography_encoded.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [19]:
geo_encoded_of = pd.DataFrame(geography_encoded.toarray(), columns=one_hot_encoder.get_feature_names_out(['Geography']))

In [20]:
geo_encoded_of

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [21]:
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_of],axis=1)

In [22]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [23]:
with open('label_encoder_gender.pkl','wb') as f:
    pickle.dump(label_encoder,f)

In [24]:
with open('onehot_encoder_geo.pkl','wb') as f:
    pickle.dump(one_hot_encoder,f)

In [25]:
X=data.drop('Exited',axis=1)
y=data['Exited']

In [26]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [27]:
X_train

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
9254,686,1,32,6,0.00,2,1,1,179093.26,1.0,0.0,0.0
1561,632,1,42,4,119624.60,2,1,1,195978.86,0.0,1.0,0.0
1670,559,1,24,3,114739.92,1,1,0,85891.02,0.0,0.0,1.0
6087,561,0,27,9,135637.00,1,1,0,153080.40,1.0,0.0,0.0
6669,517,1,56,9,142147.32,1,0,0,39488.04,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
5734,768,1,54,8,69712.74,1,1,1,69381.05,1.0,0.0,0.0
5191,682,0,58,1,0.00,1,1,1,706.50,1.0,0.0,0.0
5390,735,0,38,1,0.00,3,0,0,92220.12,1.0,0.0,0.0
860,667,1,43,8,190227.46,1,1,0,97508.04,1.0,0.0,0.0
7270,697,1,51,1,147910.30,1,1,1,53581.14,0.0,1.0,0.0

In [28]:
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)    
X_test_scaled=scaler.transform(X_test)

In [29]:
with open('scaler.pkl','wb') as f:
    pickle.dump(scaler,f)

In [32]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense   
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard 
import datetime

In [41]:
# model=Sequential([
#     Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
# ]

# )
X_train.shape[1]

12

In [44]:
model=Sequential([
    Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dense(  32, activation='relu'),
    Dense(1, activation='sigmoid')
] )

2026-02-28 17:45:53.038189: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M2
2026-02-28 17:45:53.047466: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2026-02-28 17:45:53.048842: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2026-02-28 17:45:53.050543: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2026-02-28 17:45:53.052163: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)

In [45]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [48]:
opt=tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

In [53]:
log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [56]:
early_stopping=EarlyStopping(monitor='val_loss', patience=20, restore_best_weights=True)

In [57]:
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test), epochs=100, callbacks=[early_stopping,tensorboard_callback]
)

Epoch 1/100
250/250 [==============================] - 1s 4ms/step - loss: 262.1418 - accuracy: 0.6726 - val_loss: 358.6267 - val_accuracy: 0.5870
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 215.9714 - accuracy: 0.6680 - val_loss: 86.9643 - val_accuracy: 0.8025
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 290.8365 - accuracy: 0.6674 - val_loss: 334.2529 - val_accuracy: 0.5285
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 256.1676 - accuracy: 0.6721 - val_loss: 400.9015 - val_accuracy: 0.8035
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 282.3189 - accuracy: 0.6643 - val_loss: 201.3742 - val_accuracy: 0.8035
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 436.3952 - accuracy: 0.6536 - val_loss: 640.5204 - val_accuracy: 0.7245
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 538.7219 - accuracy: 0.6616 - val_loss: 1156.9181 - val_accuracy: 0.5090
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 566.4379 - accuracy: 0.6607 - val_loss: 458.9185 - val_accuracy: 0.7410
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 900.0883 - accuracy: 0.6463 - val_loss: 394.4158 - val_accuracy: 0.7990
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 856.9567 - accuracy: 0.6604 - val_loss: 757.1556 - val_accuracy: 0.3515
Epoch 11/100
250/250 [==============================] - 1s 4ms/step - loss: 992.1714 - accuracy: 0.6506 - val_loss: 664.3209 - val_accuracy: 0.7500
Epoch 12/100
250/250 [==============================] - 1s 4ms/step - loss: 1140.8473 - accuracy: 0.6565 - val_loss: 315.7887 - val_accuracy: 0.6255
Epoch 13/100
250/250 [==============================] - 1s 4ms/step - loss: 1240.9263 - accuracy: 0.6485 - val_loss: 1152.8567 - val_accuracy: 0.4545
Epoch 14/100
250/250 [==============================] - 1s 4ms/step - loss: 1065.5011 - accuracy: 0.6589 - val_loss: 514.4120 - val_accuracy: 0.6090
Epoch 15/100
250/250 [==============================] - 1s 4ms/step - loss: 1770.0315 - accuracy: 0.6534 - val_loss: 4235.7358 - val_accuracy: 0.4795
Epoch 16/100
250/250 [==============================] - 1s 4ms/step - loss: 1859.9236 - accuracy: 0.6529 - val_loss: 1468.0742 - val_accuracy: 0.5805
Epoch 17/100
250/250 [==============================] - 1s 4ms/step - loss: 2314.2383 - accuracy: 0.6521 - val_loss: 5229.2373 - val_accuracy: 0.5595
Epoch 18/100
250/250 [==============================] - 1s 4ms/step - loss: 2757.0427 - accuracy: 0.6466 - val_loss: 884.2902 - val_accuracy: 0.5450
Epoch 19/100
250/250 [==============================] - 1s 4ms/step - loss: 1878.4863 - accuracy: 0.6554 - val_loss: 3078.3262 - val_accuracy: 0.6145
Epoch 20/100
250/250 [==============================] - 1s 4ms/step - loss: 2677.6138 - accuracy: 0.6429 - val_loss: 2000.2668 - val_accuracy: 0.8035
Epoch 21/100
250/250 [==============================] - 1s 4ms/step - loss: 3232.3420 - accuracy: 0.6550 - val_loss: 1304.7668 - val_accuracy: 0.5860
Epoch 22/100
250/250 [==============================] - 1s 4ms/step - loss: 2129.0317 - accuracy: 0.6549 - val_loss: 1529.2131 - val_accuracy: 0.6460

In [58]:
model.save('model.h5')

/Users/deepakjain/Documents/gen ai/.venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [62]:
%load_ext tensorboard
%tensorboard --logdir logs/fit/20260228-182057

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

Reusing TensorBoard on port 6007 (pid 21477), started 0:00:35 ago. (Use '!kill 21477' to kill it.)

In [61]:
%reload_ext tensorboard